Refactor panoramas processing (#240)
- Drop the video transcoding and manual GPS sync steps
- Drop GPS from the scene reconstruction when running OpenSfM
- Use trajectory alignment to find the right scene position

diff --git a/services/extractor/bin/create-camera-overrides b/services/extractor/bin/create-camera-overrides
--- a/services/extractor/bin/create-camera-overrides
+++ b/services/extractor/bin/create-camera-overrides
@@ -1,2 +1,24 @@
 #!/bin/bash
-exec python3 -m app create-camera-overrides "$@"
+# OpenSfM needs camera information for each image, like FOV etc.
+# Instead of specifying that for each image, create a single
+# catch-all file which applies to the whole dataset.
+
+if [ -z "$DATASET" ]; then
+    echo "DATASET not set, cannot continue."
+    exit 1
+fi
+
+if [ ! -f $DATASET/video.mp4 ]; then
+    echo "File $DATASET/video.mp4 not found, cannot continue."
+    exit 1
+fi
+
+if [ -f $DATASET/camera_models_overrides.json ]; then
+    echo "Found camera overrides, reusing."
+    exit 0
+fi
+
+bin/app create-camera-overrides $DATASET/video.mp4 > $DATASET/camera_models_overrides.json
+
+# Store the check-point.
+bin/upload-dataset $DATASET camera_overrides_created.txt
diff --git a/services/extractor/bin/create-masks b/services/extractor/bin/create-masks
--- a/services/extractor/bin/create-masks
+++ b/services/extractor/bin/create-masks
@@ -1,2 +1,25 @@
 #!/bin/bash
-exec python3 -m app create-masks "$@"
+# Create masks for extracted frames.
+#
+# The frames contain image from all directions, but the bottom part is static,
+# e.g. the car or the operator holding the camera, which confuses OpenSfM.
+#
+# To prevent that, we create a mask for each frame which excludes the bottom
+# part of the image (35%) from analysis.
+
+if [ -z "$DATASET" ]; then
+    echo "DATASET not set, cannot continue."
+    exit 1
+fi
+
+LOCK=masks_created.txt
+
+if [ -f $DATASET/$LOCK ]; then
+    echo "Found previously created masks, reusing."
+    exit 0
+fi
+
+echo "=== Creating masks ==="
+bin/app create-masks $DATASET
+
+bin/upload-dataset $DATASET $LOCK
